FROM docker.io/zmkfirmware/zmk-dev-arm:3.2

RUN git clone https://github.com/zmkfirmware/zmk.git /zmk && \
    git clone https://github.com/manna-harbour/miryoku_zmk.git /miryoku_zmk

ADD scripts /usr/local/bin
